# name: Release to Production
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:
# jobs:
#   setup-build-publish-deploy:
#     name: Setup, Build, Publish, and Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@master

#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v3

#     # Setup gcloud CLI
#     - name: Authenticate to Google Cloud
#       id: auth
#       uses: google-github-actions/auth@v2
#       with:
#         service_account_email: ${{ secrets.GCLOUD_EMAIL }}
#         credentials_json: ${{ secrets.GCLOUD_SA_CREDENTIALS }}
#         export_default_credentials: true

#     # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
#     - uses: google-github-actions/setup-gcloud@v2
#       name: 'Set up Cloud SDK'

#     # Configure Docker with Credentials
#     - name: Configure Docker
#       run: |
#         gcloud auth configure-docker asia-southeast2-docker.pkg.dev

#     # Build the Docker image
#     - name: Set version tag
#       id: vars
#       run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

#     - name: Build and push
#       id: docker_build
#       uses: docker/build-push-action@v2
#       with:
#         file: docker/Dockerfile
#         context: .
#         push: true
#         tags: ${{ secrets.DOCKER_IMAGENAME }}:${{ steps.vars.outputs.sha_short }}

#     # Deploy the Docker image
#     - name: Deploy
#       run: |
#         gcloud config set project ${{ secrets.GCLOUD_PROJECT }}
#         gcloud config set run/region asia-southeast1
#         gcloud run deploy ${{ secrets.SERVICE_SHORTLINK_CLOUDRUN_APPNAME }} --image ${{ secrets.DOCKER_IMAGENAME }}:${{ steps.vars.outputs.sha_short }}
